version: "3"
services:
  nginx-app:
    image: nginx-compose
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx-app
    depends_on:
      - express-app
      - nextjs-app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"

  express-app:
    image: express-compose
    build:
      context: ./express
      dockerfile: ./Dockerfile
    container_name: express-app
    depends_on:
      - database
      - cache
    restart: unless-stopped
    tty: true
    ports:
      - "5000:5000"

  nextjs-app:
    image: nextjs-compose
    build:
      context: ./nextjs
      dockerfile: ./Dockerfile
    container_name: nextjs-app
    depends_on:
      - database
      - cache
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"

  database:
    image: postgres:alpine
    container_name: database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432

  cache:
    image: "redislabs/redismod"
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  db-data:
  cache:
    driver: local
